services:
  # ================= stack =================
  dashboard:
    container_name: stack-web
    build:
      context: .
      dockerfile: ./docker/dashboard/Dockerfile
    env_file:
      - apps/dashboard/.env.docker
    environment:
      NEXT_PUBLIC_STACK_URL_DEPRECATED: http://host.docker.internal:8101
      NEXT_PUBLIC_STACK_URL: http://host.docker.internal:8102
      NEXT_PUBLIC_STACK_SVIX_SERVER_URL: http://host.docker.internal:8071
      NEXT_PUBLIC_INSECURE_COOKIE: "true" # required for local docker testing on localhost
      NEXT_PUBLIC_STACK_PROJECT_ID: internal
    ports:
      - 8101:8101
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    container_name: stack-backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    env_file:
      - apps/backend/.env.docker
    environment:
      STACK_BASE_URL: http://host.docker.internal:8102
      STACK_DATABASE_CONNECTION_STRING: postgres://postgres:password@db:5432/stackframe
      STACK_DIRECT_DATABASE_CONNECTION_STRING: postgres://postgres:password@db:5432/stackframe
      STACK_SKIP_MIGRATIONS: "false"
      STACK_RUN_SEED_SCRIPT: "true"
      # STACK_DEFAULT_ADMIN_EMAIL: admin@example.com
      # STACK_DEFAULT_ADMIN_PASSWORD: admin123
      # STACK_SIGN_UP_DISABLED: "true"
    ports:
      - 8102:8102
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stackframe
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  inbucket:
    image: inbucket/inbucket:latest
    ports:
      - 2500:2500
      - 8105:9000
      - 1100:1100
    volumes:
      - inbucket-data:/data

  # ================= svix =================

  svix-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: svix
    volumes:
      - svix-postgres-data:/var/lib/postgresql/data

  svix-redis:
    image: docker.io/redis:7-alpine
    command: --save 60 500 --appendonly yes --appendfsync everysec
    volumes:
      - svix-redis-data:/data

  svix-server:
    image: svix/svix-server
    environment:
      WAIT_FOR: "true"
      SVIX_REDIS_DSN: redis://svix-redis:6379
      SVIX_DB_DSN: postgres://postgres:password@svix-db:5432/svix
      SVIX_CACHE_TYPE: memory
      SVIX_JWT_SECRET: secret
      SVIX_LOG_LEVEL: trace
      SVIX_QUEUE_TYPE: redis
    ports:
      - 8113:8071
    depends_on:
      - svix-redis
      - svix-db

# ================= volumes =================

volumes:
  postgres-data:
    name: stack-postgres
  inbucket-data:
    name: stack-inbucket
  svix-redis-data:
    name: svix-redis
  svix-postgres-data:
    name: svix-postgres
