name: Docker Build and Push

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  build-dashboard:
    name: Docker Build and Push Dashboard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_REPO }}/stack-dashboard
          tags: |
            type=ref,event=branch
            type=sha,prefix=
            type=match,pattern=v\d.\d.\d

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./deploy/docker/dashboard/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-backend:
    name: Docker Build and Push Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_REPO }}/stack-backend
          tags: |
            type=ref,event=branch
            type=sha,prefix=
            type=match,pattern=\d.\d.\d

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./deploy/docker/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-dev:
    name: Deploy Development
    if: github.ref == 'refs/heads/self-host'
    runs-on: ubuntu-latest
    needs:
      - build-dashboard
      - build-backend
    steps:
      - name: Checkout the deployments repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GITOPS_DEPLOYMENTS_REPO }}
          token: ${{ secrets.ORG_REPO_ACCESS_PAT }}

      - name: Update dev image tag
        run: |
          # update the image tag in the dev values file
          TAG=$(echo ${{ github.sha }} | cut -c1-7)
          sed -i 's/jshimko\/stack-dashboard:.*/jshimko\/stack-dashboard:'"$TAG"'/' stack-auth/values/dev.yaml
          sed -i 's/jshimko\/stack-backend:.*/jshimko\/stack-backend:'"$TAG"'/' stack-auth/values/dev.yaml

          # commit and push the change to the deployments repo
          git config user.name "Github Actions" --local
          git config user.email github@example.com --local
          git add .
          git commit -m "[dev] Update Stack Auth image tags to $TAG"
          git push
