name: NPM Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build --filter @jshimko/stack

      - name: Publish
        run: pnpm publish --no-git-checks --access public --filter @jshimko/stack
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: gh release create ${{ github.ref }} --title "@jshimko/stack ${{ github.ref_name }}" --body "```sh\npnpm i @jshimko/stack@${{ github.ref_name }}\n```"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
